#!/bin/bash

FONT_FILE="$HOME/.fonts/Sauce\ Code\ Pro\ Medium\ Nerd\ Font\ Complete\ Mono.ttf"

if [ ! -d ~/.fonts ]; then
    mkdir ~/.fonts
fi

if [ ! -f "$FONT_FILE" ]; then
    wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Medium/complete/Sauce%20Code%20Pro%20Medium%20Nerd%20Font%20Complete%20Mono.ttf -P ~/.fonts
    fc-cache -fv
fi
